server:
  port: 8080


spring:
   datasource:
   
    driver-class-name: 
    url: 
     username:root
     password:root
  
    
   batch:
    jdbc:
      schema:
    job:
      enabled: false
    
  
 
